version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /backend
    command: dev 
    volumes: 
      - ./backend/src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mongo
    container_name: db
    platform: linux/x86_64
    ports:
      - 27017:27017
    environment:
      - MONGO_URI=mongodb://mongodb:27017/webScrapLexart
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", 'mongo --eval "db.stats()"']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE